package com.zy.rj.mapper;

import com.zy.rj.entity.Category;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Sat Oct 29 09:50:16 CST 2022
     */
    int updateByPrimaryKey(Category record);


    /**
     * 新增菜品分类
     * @param category
     * @return
     */
    int insertCategory(Category category);


    /**
     * 根据id修改菜品分类
     * @param category
     * @return
     */
    int updateCategoryById(Category category);


    /**
     * 根据id删除菜品分类
     * @param ids
     * @return
     */
    int deleteCategoryById(String ids);


    /**
     * 给菜品管理查询菜品分类名称
     * @return
     */
    List<Category> selectAllName(String type);
}