package com.zy.rj.mapper;

import com.zy.rj.entity.Dish;
import com.zy.rj.entity.DishFlavor;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    int insertSelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    Dish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    int updateByPrimaryKeySelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    int updateByPrimaryKey(Dish record);




    /**
     * 点击保存按钮添加在菜品管理模块添加菜品
     * @param dish
     * @return
     */
    int insertDish(Dish dish);


    /**
     * 点击保存按钮添加在菜品管理模块添加菜品  的口味保存
     * @param dishFlavor
     * @return
     */
    int insertDishFlavor(DishFlavor dishFlavor);



    /**
     * 菜品管理点击修改按钮显示信息
     * @param id
     * @return
     */
    Dish selectDish(String id);


    /**
     * 菜品管理点击保存按钮修改菜品信息
     * @param dish
     * @return
     */
    int updateDish(Dish dish);




    /**
     * 批量删除，根据选择的id批量删除
     * @param ids
     * @return
     */
    int deleteDishListByid(String[] ids);



    /**
     * 根据id修改状态
     * @param ids
     * @return
     */
    int updateStatusByids(String[] ids,String status);

}