package com.zy.rj.mapper;

import com.zy.rj.entity.DishFlavor;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DishFlavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    int insert(DishFlavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    int insertSelective(DishFlavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    DishFlavor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    int updateByPrimaryKeySelective(DishFlavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_flavor
     *
     * @mbggenerated Thu Jan 12 17:35:18 CST 2023
     */
    int updateByPrimaryKey(DishFlavor record);


    /**
     * 菜品添加对应口味
     * @return
     */
    int insertDishFlavor(List<DishFlavor> flavors);
}