package com.zy.rj.mapper;

import com.zy.rj.entity.SetmealDish;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SetmealDishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    int insert(SetmealDish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    int insertSelective(SetmealDish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    SetmealDish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    int updateByPrimaryKeySelective(SetmealDish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setmeal_dish
     *
     * @mbggenerated Fri Dec 23 17:26:31 CST 2022
     */
    int updateByPrimaryKey(SetmealDish record);


    /**
     * 套餐管理往setmealdish里添加菜品
     * @param setmealDishes
     * @return
     */
    int insertSetmealDish(List<SetmealDish> setmealDishes);


    /**
     * 根据id修改套餐信息,先删除修改之前的setmealdish的数据
     * @param setmealDishes
     * @return
     */
    int deleteSetmealDishByid(List<SetmealDish> setmealDishes);


    /**
     * 根据id修改套餐信息,再添加报错的setmealdish的数据
     * @param setmealDishes
     * @return
     */
    int insertUpdetaSetmealDish(List<SetmealDish> setmealDishes);


    /**
     * 删除和批量删除套餐
     * @param ids
     * @return
     */
    int deleteSetmealDishByids(String[] ids);

}