package com.zy.rj.entity;

public class DishFlavor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.dish_id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.name
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.value
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.create_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.update_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.create_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.update_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.is_deleted
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.id
     *
     * @return the value of dish_flavor.id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.id
     *
     * @param id the value for dish_flavor.id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.dish_id
     *
     * @return the value of dish_flavor.dish_id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.dish_id
     *
     * @param dishId the value for dish_flavor.dish_id
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.name
     *
     * @return the value of dish_flavor.name
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.name
     *
     * @param name the value for dish_flavor.name
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.value
     *
     * @return the value of dish_flavor.value
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.value
     *
     * @param value the value for dish_flavor.value
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.create_time
     *
     * @return the value of dish_flavor.create_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.create_time
     *
     * @param createTime the value for dish_flavor.create_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.update_time
     *
     * @return the value of dish_flavor.update_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.update_time
     *
     * @param updateTime the value for dish_flavor.update_time
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.create_user
     *
     * @return the value of dish_flavor.create_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.create_user
     *
     * @param createUser the value for dish_flavor.create_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.update_user
     *
     * @return the value of dish_flavor.update_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.update_user
     *
     * @param updateUser the value for dish_flavor.update_user
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.is_deleted
     *
     * @return the value of dish_flavor.is_deleted
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.is_deleted
     *
     * @param isDeleted the value for dish_flavor.is_deleted
     *
     * @mbggenerated Fri Nov 04 15:05:41 CST 2022
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
}