package com.zy.rj.entity;

public class Dish {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.name
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.category_id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.price
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.code
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.image
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.description
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.status
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.sort
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.create_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.update_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.create_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.update_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.is_deleted
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.id
     *
     * @return the value of dish.id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.id
     *
     * @param id the value for dish.id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.name
     *
     * @return the value of dish.name
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.name
     *
     * @param name the value for dish.name
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.category_id
     *
     * @return the value of dish.category_id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.category_id
     *
     * @param categoryId the value for dish.category_id
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.price
     *
     * @return the value of dish.price
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.price
     *
     * @param price the value for dish.price
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.code
     *
     * @return the value of dish.code
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.code
     *
     * @param code the value for dish.code
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.image
     *
     * @return the value of dish.image
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.image
     *
     * @param image the value for dish.image
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.description
     *
     * @return the value of dish.description
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.description
     *
     * @param description the value for dish.description
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.status
     *
     * @return the value of dish.status
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.status
     *
     * @param status the value for dish.status
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.sort
     *
     * @return the value of dish.sort
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.sort
     *
     * @param sort the value for dish.sort
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.create_time
     *
     * @return the value of dish.create_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.create_time
     *
     * @param createTime the value for dish.create_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.update_time
     *
     * @return the value of dish.update_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.update_time
     *
     * @param updateTime the value for dish.update_time
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.create_user
     *
     * @return the value of dish.create_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.create_user
     *
     * @param createUser the value for dish.create_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.update_user
     *
     * @return the value of dish.update_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.update_user
     *
     * @param updateUser the value for dish.update_user
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.is_deleted
     *
     * @return the value of dish.is_deleted
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.is_deleted
     *
     * @param isDeleted the value for dish.is_deleted
     *
     * @mbggenerated Fri Nov 04 08:54:24 CST 2022
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
}