package com.zy.rj.entity;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.name
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.image
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.dish_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.setmeal_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String setmealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.dish_flavor
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String dishFlavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.number
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.amount
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    private String amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.name
     *
     * @return the value of order_detail.name
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.name
     *
     * @param name the value for order_detail.name
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.image
     *
     * @return the value of order_detail.image
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.image
     *
     * @param image the value for order_detail.image
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_id
     *
     * @param orderId the value for order_detail.order_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.dish_id
     *
     * @return the value of order_detail.dish_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.dish_id
     *
     * @param dishId the value for order_detail.dish_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.setmeal_id
     *
     * @return the value of order_detail.setmeal_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getSetmealId() {
        return setmealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.setmeal_id
     *
     * @param setmealId the value for order_detail.setmeal_id
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setSetmealId(String setmealId) {
        this.setmealId = setmealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.dish_flavor
     *
     * @return the value of order_detail.dish_flavor
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getDishFlavor() {
        return dishFlavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.dish_flavor
     *
     * @param dishFlavor the value for order_detail.dish_flavor
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setDishFlavor(String dishFlavor) {
        this.dishFlavor = dishFlavor == null ? null : dishFlavor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.number
     *
     * @return the value of order_detail.number
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.number
     *
     * @param number the value for order_detail.number
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.amount
     *
     * @return the value of order_detail.amount
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.amount
     *
     * @param amount the value for order_detail.amount
     *
     * @mbggenerated Thu Feb 02 17:34:09 CST 2023
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }
}